# Logging
logging.level.com.vts.websitescanner=INFO
logging.level.org.springframework.web=WARN

# Jackson Configuration
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false

max_thread=5